-- manifest.lua — builds the SN2ModSettings registration table. Only the gates
-- live in-game; all chat/timing config is on the sidecar. SN2ModSettings renders
-- toggle/rotator (text/slider/keybind also exist); we only need toggles + one
-- rotator. main.lua writes this at module-load via settings_bridge.write_manifest.

local M = {}

M.MOD_NAME = "Sub2Chaos"
M.VERSION = "0.1.0"

function M.build()
	return {
		display = "Sub2 Chaos",
		github = "sub2_chaos",
		name = M.MOD_NAME,
		version = M.VERSION,
		settings = {
			{
				key = "enable_chaos",
				title = "Enable chaos events",
				description = "Master switch for chat-voted events.",
				type = "toggle",
				default = true,
			},
			{
				key = "enable_good",
				title = "Allow player-helping events",
				description = "Heal, invincibility, super speed, free items.",
				type = "toggle",
				default = true,
			},
			{
				key = "enable_bad",
				title = "Allow player-harming events",
				description = "Leviathan spawns, taking damage.",
				type = "toggle",
				default = true,
			},
			{
				key = "enable_chaotic",
				title = "Allow chaotic events",
				description = "Slow-motion, ghost mode, leviathan swarms.",
				type = "toggle",
				default = true,
			},
			{
				key = "enable_leviathans",
				title = "Allow leviathan spawns",
				description = "The spiciest events. Turn off to keep them out of the pool.",
				type = "toggle",
				default = true,
			},
			{
				key = "vote_duration",
				title = "Vote duration (seconds)",
				description = "How long each voting window stays open.",
				type = "slider",
				format = "integer",
				min = 5,
				max = 120,
				step = 5,
				default = 30,
			},
			{
				key = "vote_options",
				title = "Options per vote",
				description = "How many events viewers choose between each round (they type 1..N).",
				type = "slider",
				format = "integer",
				min = 2,
				max = 9,
				step = 1,
				default = 4,
			},
			{
				key = "vote_cooldown",
				title = "Cooldown between votes (seconds)",
				description = "Pause after a winner before the next vote starts. 0 = back-to-back.",
				type = "slider",
				format = "integer",
				min = 0,
				max = 120,
				step = 5,
				default = 20,
			},
			{
				key = "effect_duration_scale",
				title = "Effect duration multiplier",
				description = "Scales how long timed effects last (invincibility, super speed, slow/fast world, ghost mode). 1.0 = catalog default.",
				type = "slider",
				format = "float",
				min = 0.25,
				max = 3.0,
				step = 0.25,
				default = 1.0,
			},
			{
				key = "super_speed",
				title = "Super swim speed",
				description = "Swim speed during the Super Swim Speed event (UE units/s). ~400 is normal.",
				type = "slider",
				format = "integer",
				min = 400,
				max = 3000,
				step = 100,
				default = 1500,
				enabled_by = "enable_good",
			},
			{
				key = "slomo_fast_rate",
				title = "Fast World speed",
				description = "Time dilation for the Fast World event (>1 = faster).",
				type = "slider",
				format = "float",
				min = 1.5,
				max = 5.0,
				step = 0.5,
				default = 2.5,
				enabled_by = "enable_chaotic",
			},
			{
				key = "slomo_slow_rate",
				title = "Slow World speed",
				description = "Time dilation for the Molasses World event (<1 = slower).",
				type = "slider",
				format = "float",
				min = 0.1,
				max = 0.9,
				step = 0.1,
				default = 0.4,
				enabled_by = "enable_chaotic",
			},
			{
				key = "hurt_player_hp",
				title = "Damage event leaves you at (HP)",
				description = "Health the Take Damage event drops you to (out of 100). Lower = nastier.",
				type = "slider",
				format = "integer",
				min = 1,
				max = 90,
				step = 1,
				default = 25,
				enabled_by = "enable_bad",
			},
			{
				key = "leviathan_spawn_distance",
				title = "Leviathan spawn distance",
				description = "How far ahead of you leviathans spawn (UE units). 100 ~= 1 metre.",
				type = "slider",
				format = "integer",
				min = 400,
				max = 3000,
				step = 100,
				default = 800,
				enabled_by = "enable_leviathans",
			},
			{
				key = "swarm_size",
				title = "Leviathan swarm size",
				description = "How many leviathans the swarm event spawns.",
				type = "slider",
				format = "integer",
				min = 2,
				max = 6,
				step = 1,
				default = 3,
				enabled_by = "enable_leviathans",
			},
			{
				key = "log_level",
				title = "Log verbosity",
				type = "rotator",
				options = { "trace", "info", "warn", "error" },
				default = "info",
			},
			{
				key = "enable_hotkeys",
				title = "Enable debug hotkeys",
				description = "Manual test keys; leave off for normal play.",
				type = "toggle",
				default = false,
			},
		},
	}
end

return M
